baseURL = "http://copper.sh/"
languageCode = "en-us"
title = "Copper"
theme = "kube"
description = "Copper is a configuration validator for Kubernetes by Cloud 66"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Cloud 66"
  github = "cloud66"
  twitter = "cloud66"
  email = "hello@cloud66.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
